# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-05 08:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menucategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Descripton', ckeditor.fields.RichTextField()),
                ('url', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.')),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sub Menu',
                'verbose_name_plural': 'Sub Menus',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('url', models.SlugField(unique=True)),
                ('Descripton', ckeditor.fields.RichTextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.')),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'blank': 'BLANK', 'required': 'REQUIRED'}, max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.MenuItem'),
        ),
    ]
