# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 23:05
from __future__ import unicode_literals

import companyapp.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_bot_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Order', models.IntegerField()),
                ('url', models.URLField()),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Third Level Menus',
                'verbose_name': 'Third Level Menu',
            },
        ),
        migrations.CreateModel(
            name='menu_mid_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Order', models.IntegerField()),
                ('url', models.URLField()),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Mid Level Menus',
                'verbose_name': 'Mid Level Menu',
            },
        ),
        migrations.CreateModel(
            name='menu_top_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Order', models.IntegerField()),
                ('url', models.URLField()),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Top Menus',
                'verbose_name': 'Top Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_one', models.CharField(max_length=200)),
                ('has_level_two', models.BooleanField(default=False)),
                ('Level_two', models.CharField(max_length=200)),
                ('has_level_three', models.BooleanField(default=False)),
                ('Level_three', models.CharField(max_length=200)),
                ('BriefDisription', markdownx.models.MarkdownxField()),
                ('Disription', markdownx.models.MarkdownxField()),
                ('Icon', models.ImageField(upload_to=companyapp.models.generate_filename)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'blank': 'BLANK', 'required': 'REQUIRED'}, max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Service', models.CharField(max_length=200)),
                ('Message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Descripton', markdownx.models.MarkdownxField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.AddField(
            model_name='menu_mid_level',
            name='TopMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.menu_top_level'),
        ),
        migrations.AddField(
            model_name='menu_bot_level',
            name='MiddleMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.menu_mid_level'),
        ),
    ]
