# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.', verbose_name=reversed),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.', verbose_name=reversed),
        ),
    ]
