# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 00:13
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_pages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='Descripton',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
