# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_auto_20200306_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='The order of the menu determines where this menu appears alongside other menus.'),
        ),
    ]
