# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 00:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_auto_20180411_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='Descripton',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
