# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 13:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_auto_20180411_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_mid_level',
            options={'ordering': ['-Order'], 'verbose_name': 'Mid Level Menu', 'verbose_name_plural': 'Mid Level Menus'},
        ),
        migrations.AlterModelOptions(
            name='menu_top_level',
            options={'ordering': ['-Order'], 'verbose_name': 'Top Menu', 'verbose_name_plural': 'Top Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-created'], 'verbose_name': 'Top Menu', 'verbose_name_plural': 'Top Menus'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='Service',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='BriefDisription',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Disription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
