# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-03-07 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_menuitem_side menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucategory',
            old_name='Side Menu',
            new_name='hassidemenu',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Side Menu',
            new_name='hassidemenu',
        ),
    ]
